<../../../mkconfig

TARG=sh.dis\
	arg.dis\
	expr.dis\
	mpexpr.dis\
	file2chan.dis\
	mload.dis\
	regex.dis\
	sexprs.dis\
	std.dis\
	string.dis\
	tk.dis\
	echo.dis\
	csv.dis\
	test.dis\
	mesh.dis\
	pde.dis\
	uq.dis\
	verify.dis\
	fem.dis\
	gpu.dis\
	synth.dis\

INS=	$ROOT/dis/sh.dis\
	$ROOT/dis/sh/arg.dis\
	$ROOT/dis/sh/expr.dis\
	$ROOT/dis/sh/file2chan.dis\
	$ROOT/dis/sh/mload.dis\
	$ROOT/dis/sh/mpexpr.dis\
	$ROOT/dis/sh/regex.dis\
	$ROOT/dis/sh/std.dis\
	$ROOT/dis/sh/string.dis\
#	$ROOT/dis/sh/tk.dis\
	$ROOT/dis/sh/echo.dis\
	$ROOT/dis/sh/csv.dis\
	$ROOT/dis/sh/test.dis\
	$ROOT/dis/sh/mesh.dis\
	$ROOT/dis/sh/pde.dis\
	$ROOT/dis/sh/uq.dis\
	$ROOT/dis/sh/verify.dis\
	$ROOT/dis/sh/fem.dis\
	$ROOT/dis/sh/gpu.dis\
	$ROOT/dis/sh/synth.dis\

SYSMODULES=\
	bufio.m\
	draw.m\
	env.m\
	fem.m\
	filepat.m\
	gpu.m\
	lock.m\
	mesh.m\
	pde.m\
	sequencer.m\
	sexprs.m\
	sh.m\
	string.m\
	sys.m\
	uq.m\
	verify.m\
	tk.m\
	tkclient.m\

DISBIN=$ROOT/dis/sh

<$ROOT/mkfiles/mkdis

all:V:		$TARG

install:V:	$INS
	cp $DISBIN/sh.dis $DISBIN/..

nuke:V: clean
	rm -f $INS

clean:V:
	rm -f *.dis *.sbl

uninstall:V:
	rm -f $INS

$ROOT/dis/sh.dis:	sh.dis
	rm -f $ROOT/dis/sh.dis && cp sh.dis $ROOT/dis/sh.dis

%.dis: ${SYSMODULES:%=$MODDIR/%}
