<../mkconfig

LIB=libip.a
# readipifc.c needs hosted libc.h — omit for Inferno/os kernel builds
OFILES=\
	ctype.$O\
	eipfmt.$O\
	equivip.$O\
	parseip.$O\
	parseether.$O\
	myetheraddr.$O\
	myipaddr.$O\
	classmask.$O\
	bo.$O\
	ipaux.$O\
	ptclbsum.$O\

HFILES=\
	$ROOT/include/ip.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
