#include "ember.h"

/*
 * instruction selection tables, following limbo/optab.c.
 * disoptab is indexed by ember ast ops; columns are selected by
 * opind[type kind]: default, byte, word, big, real, string, fixed.
 */

int	opind[Tend];
uchar	isbyteinst[256];

uchar movetab[Mend][Tend] =
{
	/* Mas */
	{
		/* Tnone */	0,
		/* Tadt */	IMOVM,
		/* Tadtpick */	IMOVM,
		/* Tarray */	IMOVP,
		/* Tbig */	IMOVL,
		/* Tbyte */	IMOVB,
		/* Tchan */	IMOVP,
		/* Treal */	IMOVF,
		/* Tfn */	0,
		/* Tint */	IMOVW,
		/* Tlist */	IMOVP,
		/* Tmodule */	IMOVP,
		/* Tref */	IMOVP,
		/* Tstring */	IMOVP,
		/* Ttuple */	IMOVM,
		/* Texception */	IMOVM,
		/* Tfix */	IMOVW,
		/* Tpoly */	IMOVP,

		/* Tainit */	0,
		/* Talt */	0,
		/* Tany */	IMOVP,
	},
	/* Mcons */
	{
		/* Tnone */	0,
		/* Tadt */	ICONSM,
		/* Tadtpick */	0,
		/* Tarray */	ICONSP,
		/* Tbig */	ICONSL,
		/* Tbyte */	ICONSB,
		/* Tchan */	ICONSP,
		/* Treal */	ICONSF,
		/* Tfn */	0,
		/* Tint */	ICONSW,
		/* Tlist */	ICONSP,
		/* Tmodule */	ICONSP,
		/* Tref */	ICONSP,
		/* Tstring */	ICONSP,
		/* Ttuple */	ICONSM,
		/* Texception */	ICONSM,
		/* Tfix */	ICONSW,
		/* Tpoly */	ICONSP,

		/* Tainit */	0,
		/* Talt */	0,
		/* Tany */	ICONSP,
	},
	/* Mhd */
	{
		/* Tnone */	0,
		/* Tadt */	IHEADM,
		/* Tadtpick */	0,
		/* Tarray */	IHEADP,
		/* Tbig */	IHEADL,
		/* Tbyte */	IHEADB,
		/* Tchan */	IHEADP,
		/* Treal */	IHEADF,
		/* Tfn */	0,
		/* Tint */	IHEADW,
		/* Tlist */	IHEADP,
		/* Tmodule */	IHEADP,
		/* Tref */	IHEADP,
		/* Tstring */	IHEADP,
		/* Ttuple */	IHEADM,
		/* Texception */	IHEADM,
		/* Tfix */	IHEADW,
		/* Tpoly */	IHEADP,

		/* Tainit */	0,
		/* Talt */	0,
		/* Tany */	IHEADP,
	},
	/* Mtl */
	{
		/* Tnone */	0,
		/* Tadt */	0,
		/* Tadtpick */	0,
		/* Tarray */	0,
		/* Tbig */	0,
		/* Tbyte */	0,
		/* Tchan */	0,
		/* Treal */	0,
		/* Tfn */	0,
		/* Tint */	0,
		/* Tlist */	ITAIL,
	},
};

uchar chantab[Tend] =
{
	/* Tnone */	0,
	/* Tadt */	INEWCM,
	/* Tadtpick */	0,
	/* Tarray */	INEWCP,
	/* Tbig */	INEWCL,
	/* Tbyte */	INEWCB,
	/* Tchan */	INEWCP,
	/* Treal */	INEWCF,
	/* Tfn */	0,
	/* Tint */	INEWCW,
	/* Tlist */	INEWCP,
	/* Tmodule */	INEWCP,
	/* Tref */	INEWCP,
	/* Tstring */	INEWCP,
	/* Ttuple */	INEWCM,
	/* Texception */	INEWCM,
	/* Tfix */	INEWCW,
	/* Tpoly */	INEWCP,

	/* Tainit */	0,
	/* Talt */	0,
	/* Tany */	INEWCP,
};

uchar disoptab[Oend+1][7] =
{
	/* opcode		default	byte	word	big	real	string	fixed	*/
	/* Oadd */	[Oadd] =	{0,	IADDB,	IADDW,	IADDL,	IADDF,	IADDC,	IADDW,},
	/* Oaddas */	[Oaddas] =	{0,	IADDB,	IADDW,	IADDL,	IADDF,	IADDC,	IADDW,},
	/* Oand */	[Oand] =	{0,	IANDB,	IANDW,	IANDL,	0,	0,	0,},
	/* Oandas */	[Oandas] =	{0,	IANDB,	IANDW,	IANDL,	0,	0,	0,},
	/* Odec */	[Odec] =	{0,	ISUBB,	ISUBW,	ISUBL,	ISUBF,	0,	ISUBW,},
	/* Odiv */	[Odiv] =	{0,	IDIVB,	IDIVW,	IDIVL,	IDIVF,	0,	IDIVX,},
	/* Odivas */	[Odivas] =	{0,	IDIVB,	IDIVW,	IDIVL,	IDIVF,	0,	IDIVX,},
	/* Oeq */	[Oeq] =		{IBEQW,	IBEQB,	IBEQW,	IBEQL,	IBEQF,	IBEQC,	IBEQW,},
	/* Ogeq */	[Ogeq] =	{0,	IBGEB,	IBGEW,	IBGEL,	IBGEF,	IBGEC,	IBGEW,},
	/* Ogt */	[Ogt] =		{0,	IBGTB,	IBGTW,	IBGTL,	IBGTF,	IBGTC,	IBGTW,},
	/* Oinc */	[Oinc] =	{0,	IADDB,	IADDW,	IADDL,	IADDF,	0,	IADDW,},
	/* Oinds */	[Oinds] =	{0,	0,	IINDC,	0,	0,	0,	0,},
	/* Oindx */	[Oindx] =	{0,	0,	IINDX,	0,	0,	0,	0,},
	/* Olen */	[Olen] =	{ILENA,	0,	0,	0,	0,	ILENC,	0,},
	/* Oleq */	[Oleq] =	{0,	IBLEB,	IBLEW,	IBLEL,	IBLEF,	IBLEC,	IBLEW,},
	/* Olsh */	[Olsh] =	{0,	ISHLB,	ISHLW,	ISHLL,	0,	0,	0,},
	/* Olshas */	[Olshas] =	{0,	ISHLB,	ISHLW,	ISHLL,	0,	0,	0,},
	/* Olt */	[Olt] =		{0,	IBLTB,	IBLTW,	IBLTL,	IBLTF,	IBLTC,	IBLTW,},
	/* Omod */	[Omod] =	{0,	IMODB,	IMODW,	IMODL,	0,	0,	0,},
	/* Omodas */	[Omodas] =	{0,	IMODB,	IMODW,	IMODL,	0,	0,	0,},
	/* Omul */	[Omul] =	{0,	IMULB,	IMULW,	IMULL,	IMULF,	0,	IMULX,},
	/* Omulas */	[Omulas] =	{0,	IMULB,	IMULW,	IMULL,	IMULF,	0,	IMULX,},
	/* Oneg */	[Oneg] =	{0,	0,	0,	0,	INEGF,	0,	0,},
	/* Oneq */	[Oneq] =	{IBNEW,	IBNEB,	IBNEW,	IBNEL,	IBNEF,	IBNEC,	IBNEW,},
	/* Oor */	[Oor] =		{0,	IORB,	IORW,	IORL,	0,	0,	0,},
	/* Ooras */	[Ooras] =	{0,	IORB,	IORW,	IORL,	0,	0,	0,},
	/* Orsh */	[Orsh] =	{0,	ISHRB,	ISHRW,	ISHRL,	0,	0,	0,},
	/* Orshas */	[Orshas] =	{0,	ISHRB,	ISHRW,	ISHRL,	0,	0,	0,},
	/* Oslice */	[Oslice] =	{ISLICEA,0,	0,	0,	0,	ISLICEC,0,},
	/* Osub */	[Osub] =	{0,	ISUBB,	ISUBW,	ISUBL,	ISUBF,	0,	ISUBW,},
	/* Osubas */	[Osubas] =	{0,	ISUBB,	ISUBW,	ISUBL,	ISUBF,	0,	ISUBW,},
	/* Oxor */	[Oxor] =	{0,	IXORB,	IXORW,	IXORL,	0,	0,	0,},
	/* Oxoras */	[Oxoras] =	{0,	IXORB,	IXORW,	IXORL,	0,	0,	0,},
};

static int setisbyteinst[] = {
	IMULB,
	ISUBB,
	IADDB,
	IDIVB,
	IORB,
	IXORB,
	ISHLB,
	ISHRB,
	IMODB,
	IANDB,
	IBEQB,
	IBNEB,
	IBLTB,
	IBLEB,
	IBGTB,
	IBGEB,

	-1
};

void
optabinit(void)
{
	int i;

	opind[Tbyte] = 1;
	opind[Tint] = 2;
	opind[Tbig] = 3;
	opind[Treal] = 4;
	opind[Tstring] = 5;
	opind[Tfix] = 6;

	for(i = 0; setisbyteinst[i] >= 0; i++)
		isbyteinst[setisbyteinst[i]] = 1;
}

char *instname[256] = {
	"nop",
	"alt",
	"nbalt",
	"goto",
	"call",
	"frame",
	"spawn",
	"runt",
	"load",
	"mcall",
	"mspawn",
	"mframe",
	"ret",
	"jmp",
	"case",
	"exit",
	"new",
	"newa",
	"newcb",
	"newcw",
	"newcf",
	"newcp",
	"newcm",
	"newcmp",
	"send",
	"recv",
	"consb",
	"consw",
	"consp",
	"consf",
	"consm",
	"consmp",
	"headb",
	"headw",
	"headp",
	"headf",
	"headm",
	"headmp",
	"tail",
	"lea",
	"indx",
	"movp",
	"movm",
	"movmp",
	"movb",
	"movw",
	"movf",
	"cvtbw",
	"cvtwb",
	"cvtfw",
	"cvtwf",
	"cvtca",
	"cvtac",
	"cvtwc",
	"cvtcw",
	"cvtfc",
	"cvtcf",
	"addb",
	"addw",
	"addf",
	"subb",
	"subw",
	"subf",
	"mulb",
	"mulw",
	"mulf",
	"divb",
	"divw",
	"divf",
	"modw",
	"modb",
	"andb",
	"andw",
	"orb",
	"orw",
	"xorb",
	"xorw",
	"shlb",
	"shlw",
	"shrb",
	"shrw",
	"insc",
	"indc",
	"addc",
	"lenc",
	"lena",
	"lenl",
	"beqb",
	"bneb",
	"bltb",
	"bleb",
	"bgtb",
	"bgeb",
	"beqw",
	"bnew",
	"bltw",
	"blew",
	"bgtw",
	"bgew",
	"beqf",
	"bnef",
	"bltf",
	"blef",
	"bgtf",
	"bgef",
	"beqc",
	"bnec",
	"bltc",
	"blec",
	"bgtc",
	"bgec",
	"slicea",
	"slicela",
	"slicec",
	"indw",
	"indf",
	"indb",
	"negf",
	"movl",
	"addl",
	"subl",
	"divl",
	"modl",
	"mull",
	"andl",
	"orl",
	"xorl",
	"shll",
	"shrl",
	"bnel",
	"bltl",
	"blel",
	"bgtl",
	"bgel",
	"beql",
	"cvtlf",
	"cvtfl",
	"cvtlw",
	"cvtwl",
	"cvtlc",
	"cvtcl",
	"headl",
	"consl",
	"newcl",
	"casec",
	"indl",
	"movpc",
	"tcmp",
	"mnewz",
	"cvtrf",
	"cvtfr",
	"cvtws",
	"cvtsw",
	"lsrw",
	"lsrl",
	"eclr",
	"newz",
	"newaz",
	"raise",
	"casel",
	"mulx",
	"divx",
	"cvtxx",
	"mulx0",
	"divx0",
	"cvtxx0",
	"mulx1",
	"divx1",
	"cvtxx1",
	"cvtfx",
	"cvtxf",
	"expw",
	"expl",
	"expf",
	"self",
};
