<../../mkconfig

TARG=jl

OFILES=\
	asm.$O\
	compress.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	$TARGMODEL.$O\
	elf.$O\

HFILES=\
	l.h\
	../jc/i.out.h\
	../include/ar.h\

LIBS=bio 9			# order is important

CFLAGS=$CFLAGS -I../include -I.

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

enam.$O:	../jc/enam.c
	$CC $CFLAGS ../jc/enam.c

elf.$O:	../ld/elf.c
	$CC $CFLAGS ../ld/elf.c

$TARGMODEL.$O:	../ld/$TARGMODEL.c
	$CC $CFLAGS ../ld/$TARGMODEL.c
