implement Populationmodel;

# Nelson's Dream Machines chapter on simulation singles out the Club of
# Rome's "Limits to Growth" (the 1972 World3 study) as the archetypal
# System Dynamics feedback model: several interacting stocks - population,
# industrial capital, pollution, nonrenewable resources - each driven by
# the others, producing the famous "overshoot and collapse" curve rather
# than any single equilibrium. Unlike this danby family's usual two- or
# three-species ecology models (foodchain.b, lakepollution.b, etc), all
# four stocks here feed back on each other at once:
#   - population grows from capital/resource availability, and dies off
#     faster as pollution rises;
#   - capital is built from investment (needs both labour and resources)
#     and lost to depreciation;
#   - pollution is generated by capital's output and decays slowly;
#   - resources are a fixed reserve, drawn down by capital's extraction
#     and never replenished.
# No new harness needed - populations.b (this module's existing harness)
# already plots however many state variables a Populationmodel supplies as
# separate coloured lines over time, exactly System Dynamics' own
# characteristic chart.

include "danby/populationmodel.m";

new(): ref Model
{
	parameters := array[] of {2.0, 0.5, 3.0, 1.2, 0.3, 0.8, 0.4, 0.6};
	initial := array[] of {1.0, 0.5, 0.1, 1.0};
	return ref Model(parameters, initial);
}

title(): string
{
	return "Limits to growth: population, capital, pollution, resources";
}

statelabels(): array of string
{
	return array[] of {"population", "capital", "pollution", "resources"};
}

parameterlabels(): array of string
{
	return array[] of {
		"population growth", "base death rate", "pollution mortality",
		"investment rate", "capital depreciation",
		"pollution generation", "pollution decay", "resource extraction"
	};
}

parameterranges(): array of real
{
	return array[] of {4.0, 2.0, 6.0, 3.0, 2.0, 2.0, 2.0, 2.0};
}

Model.rhs(model: self ref Model, nil: real, state, derivative: array of real)
{
	p := model.parameter;
	population := state[0];
	capital := state[1];
	pollution := state[2];
	resources := state[3];

	# Both saturate toward 1 as capital/resources grow, and toward 0 as
	# either runs out - the same "half-saturation" shape used throughout
	# this danby family (e.g. changingenvironment.b's capacity term) so
	# growth smoothly stalls rather than going singular at zero.
	capitalfactor := capital/(capital+1.0);
	resourcefactor := resources/(resources+0.1);

	births := p[0]*population*capitalfactor*resourcefactor;
	deaths := p[1]*population*(1.0+p[2]*pollution);
	investment := p[3]*population*resourcefactor;
	depreciation := p[4]*capital;
	extraction := p[7]*capital*resourcefactor;

	derivative[0] = births-deaths;
	derivative[1] = investment-depreciation;
	derivative[2] = p[5]*capital-p[6]*pollution;
	derivative[3] = -extraction;
}

evaluate(model: ref Model, t: real, state, derivative: array of real)
{
	model.rhs(t, state, derivative);
}
